### PR TITLE
Add option to remove iframe from tabindex

### LINKED ISSUE #4388: iframe plugin: Add option to remove the iframe from tabindex
## Type of report

Feature request

## Provide description of the new feature

Some iframed content, for example complex Microsoft Power BI visualisation can be very bad with accessibility that users keyboard-tabbing through the page content without mouse may get locked in to the iframe when represented within the content of a page.

It would come handy to have an option to add `tabindex="-1"` parameter for the iframe plugin dialog options to completely force users from getting into the iframed content when using keyboard only.

This option would enhance the aceccibility of a website by preventing users experiencing accessibility issues of iframed content embedded from sources the website administrator does not have any control to.

iframe-remove-tabindex-option

### PR DESCRIPTION
**Pull request by kirkkala**
## What is the purpose of this pull request?

New feature / Addition to iframe plugin

### This PR contains

- [x] Unit tests

## Did you follow the CKEditor 4 code style guide?

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

* [#4388](https://github.com/ckeditor/ckeditor4/issues/4388): Add option to remove iframe from tabindex

## What changes did you make?

Change adds an option to remove iframe from tabindex (adds `tabindex="-1"` parameter for the iframe)

## Which issues does your PR resolve?

Closes #4388

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
Hello @kirkkala,

Thank you for contribution! :+1: However, your pull request is missing tests, see our [Contributing Code](http://docs.ckeditor.com/#!/guide/dev_contributing_code) guide for more details. You may take a look at [other Iframe plugin tests](https://github.com/ckeditor/ckeditor4/blob/major/tests/plugins/iframe/iframe.js) for inspiration :smile: 

Please also keep in mind that we're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings - this means you only need to add language entry to `en.js` and the rest will be handled automatically.

**Comment by f1ames** [comment]
@kirkkala please also note that your changes breaks current unit tests (see CI - https://travis-ci.org/github/ckeditor/ckeditor4/jobs/744719122#L295).

**Comment by kirkkala** [comment]
Thank you for the feedback @f1ames - I am very new/n00b with contributing to ckeditor. Thought just contributing back as we needed this control to tabindex on a Drupal project.

I try to find time to familiarize myself with the tests and translations (latter definitely make more sense to not update all language files 😆). But please don't hold your breath waiting for the fix - I am currently slightly busy.

**Comment by kirkkala** [comment]
@f1ames should look now better with tests and the translation files.

Also moved the new option next to other checkboxes.

**Review by Dumluregn — APPROVED** [review]
LGTM! :tada: I've applied a simple refactor, adjusted code to our style guide and added a manual test. Now let's wait for the CI before adding translation files and changelog entry.

**Comment by Dumluregn** [comment]
One of the tests [failed](https://travis-ci.org/github/ckeditor/ckeditor4/jobs/749811213) (for `exportpdf` plugin), but since it is also down for [another PR](https://travis-ci.org/github/ckeditor/ckeditor4/jobs/749811354), it looks more like a temporary CI issue and I think we are good to go :+1:

**Comment by Dumluregn** [comment]
LGTM 🎉 Thank you for contribution @kirkkala, we'll mention you in the changelog entry.

**Pull request merged**
