### PR TITLE
Use single quote instead of backticks(support IE)

### LINKED ISSUE #4953: Failing test: Use of unsupported backticks in the manual test on IE
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open: `/tests/plugins/clipboard/manual/pasteimageperformance`.

### Expected result

Editors were created correctly.

### Actual result

Editors were not created.
There is an error in the console. `Invalid character`. 

The error occurs because we are using backticks that are not supported in IE. We should change that and check for another unsupported things or skip this test in IE.

## Other details

* Browser: IE
* OS: Any
* CKEditor version: 4.17.0
* Installed CKEditor plugins: clipboard

### PR DESCRIPTION
**Pull request by sculpt0r**
## What is the purpose of this pull request?

Failing test fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
skip
```

## What changes did you make?

Replaced backticks with single quotations. Also, grouped two variables declaration into a single one.

Now the test is properly ignored.

## Which issues does your PR resolve?

Closes #4953 .

### CODE REVIEW

**Review by KarolDawidziuk — APPROVED** [review]
LGTM! 🎉 
Everything looks good and now the test is properly skipped.
I just corrected the typo in the opening `<head>` tag.

**Review by jacekbogdanski — CHANGES_REQUESTED** [review]
Test steps for this manual could be a bit improved:

> Copy an image with a size of 20-25 MB from an image editor.

* There is no "image editor" in the manual test. Maybe the author meant "file system"? But later on, we have:
> The first editor is capable of reading clipboard data copied from the file system (e.g. from Finder on macOS and from Explorer on Windows), while the second editor is not - make sure to copy an actual image into the clipboard, preferably from an image editor.
So, it may require attaching an image to the test page itself?
* It's not that easy to find an image with 20-25 MB size. Looking at how many browsers we have to test, it would be good to provide such an image within a test (e.g. for downloading from the local file host).

**Comment by sculpt0r** [comment]
So far I just used: https://effigis.com/en/solutions/satellite-images/satellite-image-samples/ - but as @Comandeer said some time ago - we shouldn't rely on external resources 😢

**Comment by sculpt0r** [comment]
>There is no "image editor" in the manual test. Maybe the author meant "file system"? 

I think, the author means application such GIMP or PS

**Comment by jacekbogdanski** [comment]
@sculpt0r if the license is MIT, you can just add this image to our repo and host it locally

**Comment by sculpt0r** [comment]
@jacekbogdanski the license is too strict for that: https://effigis.com/en/legal-restrictions/ I will find something on MIT

**Comment by sculpt0r** [comment]
@jacekbogdanski - ready for another review.
- added selfmade large image
- adjust tests description so it points to the new image
- correct some whitespace issues

**Review by jacekbogdanski — APPROVED** [review]

**Pull request merged**
