### PR TITLE
Fixed: Cannot delete paragraph before and after a widget / Delete space above widget

### LINKED ISSUE #1572: Cannot delete paragraph before and after a widget / Delete space above widget
## Are you reporting a feature request or a bug?

The old issues
"Cannot delete paragraph before and after a widget"
"Delete space above widget"
are still not fixed

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/12778
https://dev.ckeditor.com/ticket/13864

## Provide detailed reproduction steps (if any)

Just open this page:
https://sdk.ckeditor.com/samples/simplebox.html

Paste this Code:
```
<h1>&nbsp;</h1>
<div class="simplebox align-center" style="width:750px">
<h2 class="simplebox-title">Title</h2>
<div class="simplebox-content">
<p>Foo <strong>bar</strong>.</p>
<ul>
	<li>Foo!</li>
	<li>Bar!</li>
</ul>
</div>
</div>
<p>&nbsp;</p>
<div class="simplebox align-center" style="width:750px">
<h2 class="simplebox-title">Title</h2>
<div class="simplebox-content">
<p>Foo <strong>bar</strong>.</p>
<ul>
	<li>Foo!</li>
	<li>Bar!</li>
</ul>
</div>
</div>
<p>&nbsp;</p>
```

And try to delete the paragraphs before, between and after the widgets - not possible!

### Expected result

The paragraphs should be deletable

### Actual result

Paragraphs are not deleted

## Other details

Plase check my workaround in core/selection.js:

```
	// Handle left, right, delete and backspace keystrokes next to non-editable elements
	// by faking selection on them.
	function getOnKeyDownListener( editor ) {
		var keystrokes = { 37: 1, 39: 1, 8: 1, 46: 1 };

		return function( evt ) {
			var keystroke = evt.data.getKeystroke();

			// Handle only left/right/del/bspace keys.
			if ( !keystrokes[ keystroke ] )
				return;

			var sel = editor.getSelection(),
				ranges = sel.getRanges(),
				range = ranges[ 0 ];

			// Handle only single range and it has to be collapsed.
			if ( ranges.length != 1 || !range.collapsed )
				return;

			var next = range[ keystroke < 38 ? 'getPreviousEditableNode' : 'getNextEditableNode' ]();

			if ( next && next.type == CKEDITOR.NODE_ELEMENT && next.getAttribute( 'contenteditable' ) == 'false' ) {
				/* $custom: added if case to allow removal of empty paragraphs, see incidents
					https://dev.ckeditor.com/ticket/12778
					https://dev.ckeditor.com/ticket/13864 */
				if(sel._ && sel._.cache && sel._.cache.nativeSel && sel._.cache.nativeSel.baseNode && sel._.cache.nativeSel.baseNode.nodeName === 'P'){
					range.endContainer.$.remove();
				} else {
					editor.getSelection().fake( next );
					evt.data.preventDefault();
					evt.cancel();
				}
			}
		};
	}
```

### PR DESCRIPTION
**Pull request by bunglegrind**
## What is the purpose of this pull request?

fix issue #1572 

## Does your PR contain necessary tests?

yes

### This PR contains

 * [x] Unit tests

## Did you follow the CKEditor 4 code style guide?

 * [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#1572 ](https://github.com/ckeditor/ckeditor4/issues/1572): Pressing backspace and delete in an empty paragraph between two widgets now deletes the paragraph instead of selecting the next (or previous) widget 
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #1572 .

### CODE REVIEW

**Comment by Dumluregn** [comment]
Hi, thank you for the contribution!

Before we'll take a look at your work there is one thing I'd like to ask you for - target branch of this PR should be `master` instead of `major` (this is the default branch for bugfixes - I've already changed it). Could you rebase onto that branch?

**Comment by bunglegrind** [comment]
> 
> 
> Hi, thank you for the contribution!
> 
> Before we'll take a look at your work there is one thing I'd like to ask you for - target branch of this PR should be `master` instead of `major` (this is the default branch for bugfixes - I've already changed it). Could you rebase onto that branch?

Ok...I did it...well, I did something...hopefully the right steps...

**Comment by Dumluregn** [comment]
I'm afraid something is still wrong - AFAICS you've only added one commit, so it should also be the same here:
Screenshot 2020-12-11 at 14 34 20

**Comment by bunglegrind** [comment]
Yes, I can see...it looks like I'm pushing the commits I were behind...I've just follow the instruction here:

https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html

Probably that page is laking some other information concerning rebase and merge. 

Well, I will try to solve this issue in the next couple of days. Otherwise I will close this PR.

**Comment by Dumluregn** [comment]
I think it may be easiest for you to just checkout the latest `master` branch and apply your commit there (e.g. using [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick)), then you can close this PR and create a new one.

**Comment by bunglegrind** [comment]
OK.

**Pull request closed without merging**
