### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by jacekbogdanski**
Updated dev dependencies by patch/minor versions.

### CODE REVIEW

**Comment by sculpt0r** [comment]
Rebased on the newest master

**Review by sculpt0r — APPROVED** [review]
Grunt commands seem to work fine. Bender is able to run tests. Don't see any issues. But, since it is a rare case - could you @Comandeer also look at this one?

**Review by Comandeer — COMMENTED** [review]
I'm not sure if we want to bump only `package-lock.json`, leaving `package.json` totally untouched. Additionally, it's really hard to even know what was changed if only `package-lock.json` file is present as its format is nearly human-unreadable :/

**Comment by sculpt0r** [comment]
> I'm not sure if we want to bump only `package-lock.json`, leaving `package.json` totally untouched. Additionally, it's really hard to even know what was changed if only `package-lock.json` file is present as its format is nearly human-unreadable :/

Most of the time, I just traverse up to the nearest top-level package to find out which top-level package uses it. And find out that it is bender and grunt. So I just try my day-to-day routine with them...

**Review by Comandeer — APPROVED** [review]
LGTM!

**Pull request merged**
