### PR TITLE
Fix issue 4282 - During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback

### LINKED ISSUE #4282: core/scriptloader.js During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.
## Type of report

During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

## Provide detailed reproduction steps (if any)

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L61

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L155-L157

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L101-L105

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L79-L86

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/scriptloader.js#L52-L164

1. In the beginning of the scripts array processing
scriptCount = 2;
i = 0;
2. After checking the first file
scriptsCount = 1;
i = 1;
3. Next element of the array isn't checked and isn't executed "doCallback( success );"

### Expected result

*What is the expected result of the above steps?*

All the script array elements must be checked and "doCallback( success );" must be executed.

### Actual result

*What is the actual result of the above steps?*

During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

## Other details

* Browser: all
* OS: all
* CKEditor version: all
* Installed CKEditor plugins: default

### PR DESCRIPTION
**Pull request by aldoom**
Fix issue 4282 - During the uploaded scripts check the scriptLoader checks only 50 per cent of them and doesn’t execute callback.

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4282](https://github.com/ckeditor/ckeditor4/issues/4282): Describe the purpose of the pull request in a few simple sentences.
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #4282.

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
Thanks for contribution @aldoom!

Your pull request is missing tests, see our [Contributing Code](http://docs.ckeditor.com/#!/guide/dev_contributing_code) guide for more details. If you have any issues adding them, feel free to reach out so we can assist.

You may also take a look at [existing `scriptLoader` tests](https://github.com/ckeditor/ckeditor4/blob/aa1e0e7205cab2f4b6f917db1beaf0d438329114/tests/core/scriptloader.js).

**Comment by aldoom** [comment]
With patch
Firefox_Screenshot_2020-09-21T17-19-26 306Z


Without path
Firefox_Screenshot_2020-09-21T17-20-04 271Z

**Review by Comandeer — CHANGES_REQUESTED** [review]
Fix seems to work correctly, good job!

There are only some small issues:

1.  Could you move the unit test to the file dedicated to script loader (`tests/core/scriptloader.js`)?
2.  Could you rebase the branch onto `master` and target it to `master` (instead of `major`)?

**Comment by aldoom** [comment]
> 
> 
> Fix seems to work correctly, good job!
> 
> There are only some small issues:
> 
>     1. Could you move the unit test to the file dedicated to script loader (`tests/core/scriptloader.js`)?
> 
>     2. Could you rebase the branch onto `master` and target it to `master` (instead of `major`)?

Done

**Comment by f1ames** [comment]
Rebased onto latest `master`.

**Review by f1ames — APPROVED** [review]
I just slightly reworked unit tests. Also run all core tests for all the browsers and it looks good too :+1: 

LGTM :+1: Thanks @aldoom for contribution :clap: :tada:

**Pull request merged**
