### PR TITLE
T/12542

### PR DESCRIPTION
**Pull request by drfisher**
Hello!

This pull request is a continuation of this one https://github.com/ckeditor/ckeditor-dev/pull/195

One of our developers left a company so I had to create a new pull request.

### CODE REVIEW

**Comment by zipp3r** [comment]
@Reinmar, hi! Please check this PR, it's continues theme of http://dev.ckeditor.com/ticket/12524

**Comment by ericchenshine** [comment]
Hi guys, this is a nice feature to have. I am wondering any update on this feature after one and a half year? Thanks.

**Comment by mlewand** [comment]
@ericchenshine we started clearing out our PR (we got quite a few of them stacked all this time) for like 2 weeks now. for sure we will get back to this PR too. In fact I'll put it higher on our list. Make sure to subscribe the PR to get the updates.

At the same time I'd like to remind that it is always nice to put a 👍 reaction to PRs that you support so that it's more visible for us.

**Comment by Defite** [comment]
Hi, guys. There are occasional failures of random tests both in our feature branch and in your master. In some tests it looks like this:

```
Expected: undefined (undefined)
Actual:   undefined (undefined)
```

Now I have 6857 passed / 147 failed test cases in our feature branch and 6851 passed / 152 failed in your master. And the most interesting part, that if I open particular case and run it, I got 0 failed test cases. The only troublesome plugin is mathjax, it's test cases are broken.

**Comment by mlewand** [comment]
Hi @Defite - in case you're blurring the browser that might be the case, as _a lot of tests_ are depending on browser being focused. So the best way is to run it on a VM and leave the main window focused. Or just re-run these that have failed, you can scope down failed tests by adding a filter `is:failed` after your initial run.

**Comment by Defite** [comment]
Hi, @mlewand. Yes, i've run all remaining tests - now it's all ok.

**Comment by zipp3r** [comment]
Hello, @mlewand! Can you re-run travis build, and finally merge this PR?

**Comment by patricklindsay** [comment]
@drfisher @Reinmar Whatever happened to this? Be a shame to lose all the work and be great to get this feature in!

**Comment by jacekbogdanski** [comment]
It seems like this PR has been a bit stale lately. I'm freezing this PR for now, so we can get back to it once we were able to put enough attention (and :muscle:) for development.

**Pull request closed without merging**
