### PR TITLE
Fix htmldataprocessor unit test

### LINKED ISSUE #4822: Failing test: tests/core/htmldataprocessor/htmldataprocessor
Failing test: `test protected source in iframe`

```
Editor data does not match.
Expected: <!doctype html><html><head><title>foo</title></head><body><p><iframe name="aa">[[mytag]]</iframe></p></body></html> (string)
Actual:   <!doctype html><html><head><title>foo</title></head><body><p><iframe name="aa"></iframe></p></body></html> (string)  
```

## Other details

* Browser: Chrome 92.0.4515.131
* OS: Android 9

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Failing test fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [ ] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
skip
```

## What changes did you make?

We disabled any HTML content in iframe elements some time ago.

## Which issues does your PR resolve?

Closes #4822

### CODE REVIEW

**Review by Comandeer — CHANGES_REQUESTED** [review]
Although the test passes, it does no longer test protected source in `iframe`. It just tests if editor can contain empty `iframe`. Additionally test failed only on built version, which means that some of plugins changes the behaviour of data processor – maybe we should move this behaviour directly to data processor and adjust tests accordingly?

**Comment by jacekbogdanski** [comment]
As we discussed some time ago, the iframe plugin is supposed to remove all its content and its expected behavior. Most browsers are not supporting any content inside iframe and allowing it may create a security risk. Instead of changing the current test, I've removed `iframe` plugin from `htmldataprocessor` test and added test coverage to `iframe` plugin itself. Note that I've had to make some adjustments to the test suite itself, as it was working in some cases accidentally (by reusing previous tests HTML for editing dialogs).

**Review by Comandeer — CHANGES_REQUESTED** [review]
Changes in `/tests/core/htmldataprocessor/htmldataprocessor` seems fine. However, the tests in `/tests/plugins/iframe/iframe` does not work in IE 8-10 after the changes.

**Review by Comandeer — APPROVED** [review]
LGTM!

**Pull request merged**
