### PR TITLE
Standardize test asset image

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Task

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

N/A

## What changes did you make?

I've updated the test fixtures for PfW blob URL test.

### CODE REVIEW

**Comment by jacekbogdanski** [comment]
Let's use https://en.wikipedia.org/wiki/Lenna image that is often used in our tests codebase.

**Comment by Comandeer** [comment]
Instead of Lenna I've used [old CKE4 logo](https://github.com/ckeditor/ckeditor4/pull/5152/files#diff-c9a87bbb637de9e25a638f4c1685172c07b71e577ebbea492703d9328e3ccee8).

**Comment by jacekbogdanski** [comment]
@KarolDawidziuk could you take a look at these changes and merge them if everything is alright?

**Comment by Comandeer** [comment]
Rebased onto the latest `master`.

**Review by KarolDawidziuk — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
