### PR TITLE
Fix incorrect handling of HSL/HSLA values

### LINKED ISSUE #4596: Incorrect handling of HSL/HSLA values
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open browser console.
2. Go to https://jsfiddle.net/7Ljwqmtz/
3. Check the console.

### Expected result

There should be `false` in the console, as the color is incorrect.

### Actual result

There is `true`

## Other details

According to the specification, [HSL format accept only percentage as second and third parameter](https://drafts.csswg.org/css-color/#the-hsl-notation).

* CKEditor version: 4.16.0

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4596](https://github.com/ckeditor/ckeditor4/issues/4596): Fixed: incorrect handling of HSL/HSLA values.
```

## What changes did you make?

During fixing the issue with accepting non-percentage values, I've discovered that [hue can be passed also as degrees](https://drafts.csswg.org/css-color/#typedef-hue). So I've decided to fix it as well.

And I thought that the good idea would be to fix it by enhancing our regex. Oh, how naive I was…! Yet, I've managed to enhance our regex. And added some docs to it for the next naive one that would think the same thing as me.

## Which issues does your PR resolve?

Closes #4596.

Note: this PR is a bug fix, but it's targeted to `major` as already merged changes (especially #4599) heavily influenced the proposed solution.

### CODE REVIEW

**Comment by Dumluregn** [comment]
Rebased onto latest `major`.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
The fix looks good 👍🏻 Two things left to do:
1) We need to update docs:
* hue - can accept `deg`
* saturation and lightness - only take `%` values
* alpha - can accept both fraction and percentage.

2) File with tests grew too much and becomes hard to maintain, I think it's time to split it into a few smaller ones. My proposal is based on the type of tests, so three files (for now):

* color conversion
* color channels
* color format

  Still, feel free to propose another division if you find out anything reasonable.

**Comment by Comandeer** [comment]
I've divided tests into three files:

*   `color.js` – more general tests (like invalid formats etc.),
*   `conversion.js` – tests connected with conversion,
*   `channels.js` – test connected with validating extracted channels.

I've also moved them to the new dir, `/tests/core/tools/color`.

> We need to update docs

I'm not sure which docs you're referring to. If you mean API docs, then IMO they're correct. We state in them that we support RGB and HSL formats – and that's still true (even more true than before, as our understanding of these formats was different than what it's in the spec).

**Review by Dumluregn — APPROVED** [review]
LGTM! 🎉 

> I've divided tests into three files:

👍🏻 

> I'm not sure which docs you're referring to.

Took me a while, but now I see that even if e.g. saturation is passed in `%`, we save it in channel as integer value (same for lightness etc.). So you're right that docs are fine.

**Pull request merged**
