### PR TITLE
Fix Cannot read property 'blur' of null in focusmanager

### LINKED ISSUE #3686: Cannot read property 'blur' of null in focusManager
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Reported in https://github.com/concrete5/concrete5/issues/8271 but it's very hard to be replicated.
Basically, I think that this can be replicated with these steps:
- open a CKEditor instance
- hit the `Link` toolbar button
- click on an input field (for example `Display Text`) when there's a hook in the page that destroys CKEditor when an input field is focuses.

### Expected result

No errors occur.

### Actual result

Error logged in the developer console:

```
ckeditor.js:258 Uncaught TypeError: Cannot read property 'blur' of null
    at CKEDITOR.focusManager.remove (ckeditor.js:258)
    at N (ckeditor.js:595)
    at CKEDITOR.dialog.hide (ckeditor.js:616)
    at Object.<anonymous> (ckeditor.js:648)
    at Object.l (ckeditor.js:10)
    at Object.fire (ckeditor.js:12)
    at a.destroy (ckeditor.js:289)
```

## Other details

* Browser: any
* OS: any
* CKEditor version: 4.12
* Installed CKEditor plugins: `a11yhelp`, `about`, `ajax`, `autocomplete`, `autogrow`, `autolink`, `basicstyles`, `bidi`, `blockquote`, `button`, `clipboard`, `colorbutton`, `colordialog`, `concrete5filemanager`, `concrete5inline`, `concrete5link`, `concrete5styles`, `concrete5uploadimage`, `contextmenu`, `dialogadvtab`, `dialogui`, `dialog`, `divarea`, `div`, `elementspath`, `emoji`, `enterkey`, `entities`, `fakeobjects`, `filebrowser`, `filetools`, `find`, `flash`, `floatingspace`, `floatpanel`, `font`, `format`, `horizontalrule`, `htmlwriter`, `iframe`, `image2`, `image`, `indentblock`, `indentlist`, `indent`, `justify`, `language`, `lineutils`, `link`, `listblock`, `liststyle`, `list`, `magicline`, `maximize`, `menubutton`, `menu`, `newpage`, `normalizeonchange`, `notificationaggregator`, `notification`, `pagebreak`, `panelbutton`, `panel`, `pastefromword`, `pastetext`, `placeholder`, `popup`, `preview`, `print`, `removeformat`, `resize`, `richcombo`, `save`, `scayt`, `selectall`, `showblocks`, `showborders`, `smiley`, `sourcearea`, `sourcedialog`, `specialchar`, `stylescombo`, `tableresize`, `tableselection`, `tabletools`, `table`, `tab`, `textmatch`, `textwatcher`, `toolbar`, `undo`, `uploadimage`, `uploadwidget`, `widgetselection`, `widget`, `wsc`, `wysiwygarea`, `xml`

### PR DESCRIPTION
**Pull request by mlocati**
## What is the purpose of this pull request?

Fix #3686

## Does your PR contain necessary tests?

I really don't know how to implement a test for such an edge case.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What is the proposed changelog entry for this pull request?

```
*[#3686](https://github.com/ckeditor/ckeditor4/issues/3686): Fix "Cannot read property 'blur' of null in focusmanager" error that may occur in some edge case.
```

## What changes did you make?

A simple check that an object is not null.

## Which issues your PR resolves?

Closes #3686.

### CODE REVIEW

**Comment by Dumluregn** [comment]
Hi @mlocati,
unfortunately this pull request is missing tests. Please see our [Contributing Code guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html) (especially part about [tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests)) for more details. Thank you!

**Comment by mlocati** [comment]
I don't have the time to study how to replicate this issue and how to write tests. Feel free to close this issue if you prefer

**Comment by jacekbogdanski** [comment]
@mlocati thanks for the contribution! We will take a closer look at the changes once we will have a bit of time as we are heavily involved in the current CKE4 development. If you find out some resources to write tests, we would be glad for additional PR improvements.

**Comment by jacekbogdanski** [comment]
Due to the fact that the issue is hardly reproducible, I'm freezing this PR. However, if you find out some time to write tests or you see this issue as a blocker, please tell, so we can reopen this PR.

**Pull request closed without merging**
