### PR TITLE
Fix z-index of parentDialog when baseFloatZIndex is configured instea…

### LINKED ISSUE #5365: config.baseFloatZIndex issues with two dialogs causes app to become unusable
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Using `config.baseFloatZIndex`does not work when opening two dialogs.
See https://jsfiddle.net/9ecb0w8f/ where I only set the baseFloatZIndex and nothing else.
Then do the following to reproduce the bug

1. create a table (columns/rows doesn't matter)
2. richt click any cell
3. go to cell properties
4. for background color click the 'Choose' button
5. pick any color and click Ok (or click cancel)

### Expected result
Color is filled in and the color picker is closed correctly

### Actual result
The color is filled but the popup background color div stays (because of z-index) which makes the app unusable

## Other details
the z-index of the background of the color picker stays at the configured baseFloatZIndex while the dialog_container of the cell properties dialog has a z-index removed (this happens when we close the color picker popup) but has a default (lower one) configured on the .cke.dialog.container css class. See these screenshots:

image (5)
image (3)

### PR DESCRIPTION
**Pull request by JenoDK**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5365](https://github.com/ckeditor/ckeditor4/issues/5365): Prevent CKEditor from being stuck when using baseFloatZIndex and opening two dialogs.
```

## What changes did you make?

In the dialog hide function I set the z-index of the `this._.parentDialog.getElement()` instead of removing it.
I use the same value used for the `parentElement`.

I am not sure if this is the correct way to solve this so feel free to point me in the right direction.

## Which issues does your PR resolve?

Closes #5365

### CODE REVIEW

**Review by Comandeer — CHANGES_REQUESTED** [review]
Hi, @JenoDK! Thanks for your contribution!

However, all changes to the CKEditor 4 codebase need to be tested. There is a [guide about creating tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test) in the docs. Could I ask you to add tests to your PR?

**Comment by JenoDK** [comment]
Hi @Comandeer 

While setting up the test environment and running
`bender server run`
I get this error
```
(node:39077) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39077) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(node:39077) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(node:39077) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/dekeyzer/git/ckeditor4/node_modules/uid/package.json' of 'yes'. Please either fix that or report it to the module author
Potentially unhandled rejection [1] ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/Users/dekeyzer/git/ckeditor4/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/dekeyzer/git/ckeditor4/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/dekeyzer/git/ckeditor4/node_modules/gerard/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
/opt/homebrew/bin/jenv
```

**Comment by Comandeer** [comment]
Which version of Node do you use? Unfortunately, Bender requires Node 10 for now.

**Comment by JenoDK** [comment]
Ah that makes sense, I'm using node 16. I'll look into running node 10 for this.

**Comment by JenoDK** [comment]
@Comandeer I wasn't able to run node 10 on my M1 Macbook so I just added some manual tests. I hope this is fine.

**Review by Comandeer — APPROVED** [review]
LGTM! I've added a unit test and slightly simplified the manual one. The fix itself looks good.

Once again, thanks for your contribution, @JenoDK!

**Comment by JenoDK** [comment]
Thanks @Comandeer for the help and additions!

**Pull request merged**
